export const words = [
        "abba", // A
        "agnadio", // O
        "batto", // O
        "bazzo", // O
        "baldoz", // X
        "becca", // A
        "beccez", // X
        "bisa", // A
        "bectra", // A
        "betzo", // O
        "blut", // X
        "brabbo", // O
        "brozza", // A
        "buzzen", // X
        "caccior", // X
        "cazza", // A
        "ceglo", // O
        "cegloz", // X
        "cenz", // X
        "cetto", // O
        "chetta", // A
        "denbo", // O
        "denbro", // O
        "denez", // X
        "denix", // X
        "denzo", // O
        "drocca", // A
        "drogo", // O
        "drozzo", // O
        "feglia", // A
        "frocco", // O
        "frozza", // A
        "ghetto", // O
        "ghettro", // O
        "ghezz", // X
        "guffo", // O
        "guzzo", // O
        "lagba", // A
        "lagozzo", // O
        "lagtro", // O
        "lert", // X
        "lodda", // A
        "lodro", // O
        "lodza", // A
        "luchen", // X
        "lucho", // O
        "luchoz", // X
        "luchro", // O
        "muzzon", // X
        "muzzox", // X
        "mezarco", // X
        "neddo", // O
        "nedzo", // O
        "nuccez", // X
        "nuccel", // X
        "nuccen", // X
        "nuccix", // X
        "nuccio", // O
        "nuccol", // X
        "nuddo", // O
        "pizzal", // X
        "pizzan", // X
        "pizzel", // X
        "pizzix", // X
        "plozza", // A
        "pozzel", // X
        "pozzix", // X
        "pratzo", // O
        "pritta", // A
        "rabbo", // O
        "rabtro", // O
        "rabza", // A
        "rabzot", // X
        "scendro", // O
        "scenza", // A
        "snatto", // O
        "snedro", // O
        "snorba", // A
        "snotto", // O
        "teglio", // O
        "tenbra", // A
        "tenoz", // X
        "tenza", // A
        "tenzox", // X
        "tondel", // X
        "tondix", // X
        "trunbo", // O
        "tronca", // A
        "trunel", // X
        "trunzo", // O
        "vettro", // O
        "vexzo", // X
        "zanzo", // O
        "zennox", // X
        "zennut", // X
        "zorba", // A
        "zorbix", // X
        "zorza", // A
        "zotta", // A
        "zundro", // O
        "zupen", // X
        "zuzza", // A
        "zuzzon", // X
        "zuzzox", // X
        "zenko", // O
        "zetta", // A
    ];