export const words = [
    "ab", // X
    "abbaba", // A
    "ac", // X
    "agnadio", // O
    "albro", // O
    "aldrenna", // A
    "alemborda", // A
    "alfetron", // X
    "altronda", // A
    "ancet", // X
    "androlla", // A
    "ap", // X
    "arbol", // X
    "arcen", // X
    "ardenbol", // X
    "axx", // X
    "baldoz", // X
    "balfo", // O
    "baltronda", // A
    "batto", // O
    "bazzo", // O
    "bec", // X
    "becca", // A
    "beccez", // X
    "bectra", // A
    "bel", // X
    "belgo", // O
    "beltroma", // A
    "beltrondo", // O
    "bembrolla", // A
    "bendracco", // O
    "betzo", // O
    "bip", // X
    "bisa", // A
    "blonderra", // A
    "blondressa", // A
    "blut", // X
    "bof", // X
    "bontra", // A
    "brabbo", // O
    "breldonna", // A
    "breldo", // O
    "bremfalto", // O
    "brendolla", // A
    "brondello", // O
    "brozza", // A
    "buf", // X
    "buzzen", // X
    "cac", // X
    "caccior", // X
    "caldremba", // A
    "caldrenna", // A
    "candra", // A
    "cappa", // A
    "cazzaccio", // O
    "ceglo", // O
    "cegloz", // X
    "cembralda", // A
    "cembrando", // O
    "cendrolfa", // A
    "cendrolla", // A
    "cenz", // X
    "cep", // X
    "cetto", // O
    "chelta", // A
    "chetta", // A
    "clambo", // O
    "clembro", // O
    "clendorra", // A
    "clendo", // O
    "cof", // X
    "colfer", // X
    "craldenna", // A
    "crondel", // X
    "crondella", // A
    "cul", // X
    "dac", // X
    "dafro", // O
    "dal", // X
    "daltrenna", // A
    "dembro", // O
    "denbo", // O
    "denbro", // O
    "denez", // X
    "denix", // X
    "denzo", // O
    "dof", // X
    "dondra", // A
    "dreffo", // O
    "drembolfa", // A
    "drembolla", // A
    "drendolla", // A
    "drendracco", // O
    "drocca", // A
    "drogo", // O
    "drozzo", // O
    "dup", // X
    "eb", // X
    "ec", // X
    "efron", // X
    "elbot", // X
    "eldremba", // A
    "eltramba", // A
    "eltrembol", // X
    "empal", // X
    "en", // X
    "endro", // O
    "endrolfa", // A
    "ep", // X
    "ergun", // X
    "faldremba", // A
    "faldo", // O
    "faldrenna", // A
    "fec", // X
    "feglia", // A
    "feltra", // A
    "feltronda", // A
    "fembro", // O
    "fendralto", // O
    "fendrolla", // A
    "fer", // X
    "flacco", // O
    "fladrenna", // A
    "flandorra", // A
    "fol", // X
    "fralda", // A
    "fraldenna", // A
    "fraldesso", // O
    "frembo", // O
    "frendolca", // A
    "frendolla", // A
    "frocco", // O
    "frozza", // A
    "fup", // X
    "gac", // X
    "galbon", // X
    "galdrenna", // A
    "galtronda", // A
    "gembro", // O
    "gendrolfa", // A
    "ghetto", // O
    "ghettro", // O
    "ghezz", // X
    "gil", // X
    "glaffa", // A
    "glemborda", // A
    "glembrola", // A
    "glendo", // O
    "glonderra", // A
    "glondressa", // A
    "gof", // X
    "gralto", // O
    "greldamba", // A
    "greldonna", // A
    "grondella", // A
    "grondesso", // O
    "grumba", // A
    "guffo", // O
    "gul", // X
    "guzzo", // O
    "haldo", // O
    "haldrenna", // A
    "hembra", // A
    "hembrolla", // A
    "hol", // X
    "hondel", // X
    "hondrella", // A
    "hufon", // X
    "id", // X
    "ilber", // X
    "ildrenna", // A
    "imbot", // X
    "in", // X
    "incral", // X
    "indrembra", // A
    "ip", // X
    "irmon", // X
    "lac", // X
    "lagba", // A
    "lagozzo", // O
    "lagtro", // O
    "landra", // A
    "landressa", // A
    "lantronda", // A
    "lef", // X
    "lembo", // O
    "lendroma", // A
    "lendrossa", // A
    "lert", // X
    "lod", // X
    "lodda", // A
    "lodro", // O
    "lodza", // A
    "lop", // X
    "luchen", // X
    "lucho", // O
    "luchoz", // X
    "luchro", // O
    "luf", // X
    "maldro", // O
    "maldrenna", // A
    "mandra", // A
    "mandressa", // A
    "mantrolla", // A
    "mec", // X
    "melfa", // A
    "meltrando", // O
    "meltronna", // A
    "membrolla", // A
    "mezarco", // X
    "mil", // X
    "mof", // X
    "moldembra", // A
    "moltra", // A
    "moltrenna", // A
    "mondel", // X
    "mondressa", // A
    "mup", // X
    "muzzon", // X
    "muzzox", // X
    "nac", // X
    "nalbo", // O
    "naldrenna", // A
    "neddo", // O
    "nedzo", // O
    "nef", // X
    "nembra", // A
    "nembrolla", // A
    "nendrossa", // A
    "nol", // X
    "nuccec", // X
    "nuccel", // X
    "nuccen", // X
    "nuccez", // X
    "nuccio", // O
    "nuccix", // X
    "nuccol", // X
    "nuddo", // O
    "nup", // X
    "ob", // X
    "oc", // X
    "of", // X
    "ol", // X
    "olbran", // X
    "oldrenna", // A
    "oltrenda", // A
    "ondrel", // X
    "ondremba", // A
    "op", // X
    "orbat", // X
    "ordembol", // X
    "ox", // X
    "pal", // X
    "paldon", // X
    "paldrenna", // A
    "paltronda", // A
    "pec", // X
    "peltra", // A
    "peltronca", // A
    "pendro", // O
    "pendrolla", // A
    "pendrossa", // A
    "pil", // X
    "pizzal", // X
    "pizzan", // X
    "pizzel", // X
    "pizzix", // X
    "ploffa", // A
    "plonderra", // A
    "plondressa", // A
    "plozza", // A
    "pof", // X
    "pozzel", // X
    "pozzix", // X
    "praldenna", // A
    "praldressa", // A
    "pratzo", // O
    "prenda", // A
    "prendolfa", // A
    "prendossa", // A
    "pritta", // A
    "pul", // X
    "quandel", // X
    "quandro", // O
    "quandrolla", // A
    "quembro", // O
    "quelfa", // A
    "quembrola", // A
    "quembrossa", // A
    "rab", // X
    "rabbo", // O
    "rabtro", // O
    "rabza", // A
    "rabzot", // X
    "raldrenna", // A
    "raldex", // X
    "raltronda", // A
    "rec", // X
    "rembro", // O
    "rendoltra", // A
    "rendrossa", // A
    "rof", // X
    "rol", // X
    "roldan", // X
    "rondrella", // A
    "rup", // X
    "sac", // X
    "salbo", // O
    "saldrenna", // A
    "saltronda", // A
    "scembolta", // A
    "scembrolla", // A
    "scendro", // O
    "scenza", // A
    "sembra", // A
    "sembrolla", // A
    "sendrolla", // A
    "sendrossa", // A
    "sep", // X
    "sfalda", // A
    "sfaldonna", // A
    "sfaldressa", // A
    "snal", // X
    "snatto", // O
    "snedro", // O
    "snorba", // A
    "snorbrella", // A
    "snotto", // O
    "sof", // X
    "sol", // X
    "sondra", // A
    "sondressa", // A
    "sontrolla", // A
    "spaldo", // O
    "spaldrenna", // A
    "splendoba", // A
    "splendorra", // A
    "strembo", // O
    "strendola", // A
    "strendrola", // A
    "strondella", // A
    "strondressa", // A
    "sul", // X
    "tac", // X
    "talfo", // O
    "taldrenna", // A
    "taltronda", // A
    "tef", // X
    "teglio", // O
    "tel", // X
    "tembra", // A
    "tembrolla", // A
    "tenbra", // A
    "tendrossa", // A
    "tenoz", // X
    "tenza", // A
    "tenzox", // X
    "toc", // X
    "tol", // X
    "tondel", // X
    "tondix", // X
    "tondressa", // A
    "tralba", // A
    "traldrenna", // A
    "treldamba", // A
    "treldrossa", // A
    "trondello", // O
    "tronca", // A
    "trondressa", // A
    "trunbo", // O
    "trunel", // X
    "trunzo", // O
    "tuc", // X
    "uf", // X
    "ul", // X
    "uldren", // X
    "uldrenna", // A
    "ultronda", // A
    "umbral", // X
    "umbrolla", // A
    "up", // X
    "vac", // X
    "val", // X
    "valdro", // O
    "valdrenna", // A
    "valtronda", // A
    "vembra", // A
    "vembraldo", // O
    "vembrolla", // A
    "vendrolla", // A
    "vendrossa", // A
    "vep", // X
    "vettro", // O
    "vexzo", // X
    "vof", // X
    "vol", // X
    "voldan", // X
    "voldembra", // A
    "voldressa", // A
    "vul", // X
    "weldra", // A
    "weldronda", // A
    "weldrossa", // A
    "wendol", // X
    "wendrolla", // A
    "wol", // X
    "woldrenna", // A
    "xalbo", // O
    "xaldrenna", // A
    "xembra", // A
    "xembraldo", // O
    "xembrolla", // A
    "xendro", // O
    "xendrossa", // A
    "xol", // X
    "xoldrenna", // A
    "yaldo", // O
    "yaldrenna", // A
    "yembra", // A
    "yembrolla", // A
    "yembronda", // A
    "yendrossa", // A
    "yoldrenna", // A
    "zac", // X
    "zaldon", // X
    "zaldrenna", // A
    "zanzo", // O
    "zef", // X
    "zeldrossa", // A
    "zenko", // O
    "zennox", // X
    "zennut", // X
    "zetta", // A
    "zol", // X
    "zoldrenna", // A
    "zoltrenda", // A
    "zoltrossa", // A
    "zorba", // A
    "zorbix", // X
    "zorza", // A
    "zotta", // A
    "zul", // X
    "zuldrenna", // A
    "zundro", // O
    "zup", // X
    "zupen", // X
    "zuzza", // A
    "zuzzon", // X
    "zuzzox", // X
    "▓█▓▒░░▒▓█▓▒░▒", // X
    "   ░░  ░░░",
    "░██    ░██",
    "▐░█▄▄▄▄▄▄▄█░▌"
];
